-- EXERCITO BRASILEIRO
-- EB: ACRE (ID: 1)
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('1', '69980000', 'RUA PEDRO TELES', 'CENTRO', '84');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('1', '4ª DELEGACIA DO SERVIÇO MILITAR DA 31ª CSM', '4ª DSM/31ª CSM', '085', '2', '1', '1');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('2', '69980000', 'AVENIDA 25 DE AGOSTO', 'AEROPORTO VELHO', '84');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('2', '61º BATALHÃO DE INFANTARIA DE SELVA', '61º BIS', '3224', '2', '1', '2');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('3', '69918093', 'AVENIDA NAÇÕES UNIDAS', '7º BEC', '94');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('3', '7º BATALHÃO DE ENGENHARIA E CONSTRUÇÃO', '7º BEC', '2100', '2', '1', '3');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('4', '69900679', 'RUA COLOMBIA', 'BOSQUE', '94');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('4', 'COMANDO DE FRONTEIRA ACRE E 4º BATALHÃO DE INFANTARIA DE SELVA', 'CMDO FRON AC/4º BIS', 'S/N', '2', '1', '4');

-- EB: ALAGOAS (ID: 2)
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('5', '57025300', 'AVENIDA VIEIRA PERDIGÃO', 'CENTRO', '147');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('5', '1ª DELEGACIA DO SERVIÇO MILITAR DA 20ª CSM', '1ª DSM/20ª CSM', '392', '2', '2', '5');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('6', '57020650', 'PRAÇA OLAVO BILAC', 'CENTRO', '147');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('6', '20ª CIRCUNSCRIÇÃO DE SERVIÇO MILITAR', '20ª CSM', '33', '2', '2', '6');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('7', '57690000', 'AVENIDA PARAÍBA', 'NOVA OLINDA', '104');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('7', '4ª DELEGACIA DO SERVIÇO MILITAR DA 20ª CSM', '4º DSM/20ª CSM', '33', '2', '2', '7');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('8', '57050000', 'AVENIDA FERNANDES LIMA', 'FAROL', '147');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('8', '59º BATALHÃO DE INFANTARIA MOTORIZADO', '59º BIMTZ', '1970', '2', '2', '8');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('9', '57300000', 'RUA PRESIDENTE MEDICI', 'ALTO CRUZEIRO', '103');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('9', '5ª DELEGACIA DO SERVIÇO MILITAR DA 20ª CSM', '5º DSM/20ª CSM', '80', '2', '2', '9');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('10', '57480000', 'PRAÇA DA MATRIZ', 'CENTRO', '126');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('10', '6ª DELEGACIA DO SERVIÇO MILITAR DA 20ª CSM', '6º DSM/20ª CSM', '8', '2', '2', '10');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('11', '57304410', 'RUA SGT BENEVIDES MONTES', 'PRIMAVERA', '103');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('11', 'TIRO DE GUERRA DE ARAPIRACA', 'TG 07015', 'S/N', '2', '2', '11');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('12', '57600200', 'RUA LUIZ PINTO DE ANDRADE', 'CENTRO', '167');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('12', 'TIRO DE GUERRA DE PALMEIRA DOS ÍNDIOS', 'TG 07007', '39', '2', '2', '12');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('13', '57200000', 'PRAÇA MAL DEODORO', 'CENTRO', '173');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('13', 'TIRO DE GUERRA DE PENEDO', 'TG 07008', '23', '2', '2', '13');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('14', '57860010', 'RUA VEREADOR JOAO FERREIRA', 'CENTRO', '189');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('14', 'TIRO DE GUERRA DE SÃO JOSÉ DA LAJE', 'TG 07009', 'S/N', '2', '2', '14');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('15', '57265000', 'RUA VEREADOR MIGUEL FERNANDES TAVÁRES', 'CENTRO', '199');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('15', 'TIRO DE GUERRA DE TEOTÔNIO VILELA', 'TG 07022', '519', '2', '2', '15');

-- EB: AMAZONAS (ID: 3)
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('16', '69065100', 'AVENIDA CARVALHO LEAL', 'CACHOEIRINHA', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('16', '12ª INSPETORIA DE CONTABILIDADE E FINANÇAS DO EXÉRCITO', '12ª ICFEX', '740', '2', '3', '16');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('17', '69029290', 'AVENIDA MARECHAL BITTENCOURT', 'SANTO ANTONIO', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('17', '12º BATALHÃO DE SUPRIMENTO', '12º BSUP', '55', '2', '3', '17');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('18', '69037000', 'AVENIDA CORONEL TEIXEIRA', 'PONTA NEGRA', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('18', '1º BATALHÃO DE COMUNICAÇÕES DE SELVA', '1º BCOM SL', '5345', '2', '3', '18');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('19', '69033000', 'AVENIDA SÃO JORGE', 'SÃO JORGE', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('19', '1º BATALHÃO DE INFANTARIA DE SELVA (AEROMÓVEL)', '1º BIS', '650', '2', '3', '19');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('20', '69005320', 'RUA BERNARDO RAMOS', 'CENTRO', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('20', '29º CIRCUNSCRIÇÃO DE SERVIÇO MILITAR', '29º CSM', '253', '2', '3', '20');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('21', '69037000', 'AVENIDA CORONEL TEIXEIRA', 'COMPENSA', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('21', '3ª COMPANHIA DE FORÇAS ESPECIAIS', '3º CIA F ESP', '8148', '2', '3', '21');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('22', '69005430', 'RUA VISCONDE DE MAUÁ', 'CENTRO', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('22', '3ª DELEGACIA DO SERVIÇO MILITAR DA 29ª CSM', '3º DSM/29ª CSM', 'S/N', '2', '3', '22');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('23', '69029000', 'AVENIDA MARECHAL BITTENCOURT', 'COMPENSA', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('23', '4º CENTRO DE GEOINFORMAÇÃO', '4º CGEO', '97', '2', '3', '23');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('24', '69030480', 'RUA PLÁCIDO DE CASTRO', 'PONTA NEGRA', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('24', '4º COMPANHIA DE INTELIGÊNCIA', '4º CIA INTLG', '4715', '2', '3', '24');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('25', '69074160', 'ESTRADA DO PAREDÃO', 'COLÔNIA OLIVEIRA MACHADO', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('25', '4º BATALHÃO DE AVIAÇÃO DO EXÉRCITO', '4º BAVEX', '828', '2', '3', '25');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('26', '4º CENTRO DE TELEMÁTICA DE ÁREA', '4º CTA', '4715', '2', '3', '18');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('26', '69030460', 'AVENIDA SÃO JORGE', 'SÃO JORGE', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('27', '7º BATALHÃO DE POLÍCIA DO EXÉRCITO', '7º BPE', '1944', '2', '3', '26');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('28', 'CENTRO DE EMBARCAÇÕES DO EXÉRCITO', 'CECMA', 'S/N', '2', '3', '18');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('29', 'CENTRO DE INSTRUÇÃO DE GUERRA NA SELVA', 'CIGS', '750', '2', '3', '19');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('27', '69010070', 'RUA JOSÉ CLEMENTE', 'CENTRO', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('30', 'COLÉGIO MILITAR DE MANAUS', 'CMM', '157', '2', '3', '27');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('31', 'COMANDO DA 12ª REGIÃO MILITAR', '12ª RM', '6155', '2', '3', '18');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('32', 'COMANDO DO 2º GRUPAMENTO DE ENGENHARIA', '2ª GPT E', '6800', '2', '3', '18');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('33', 'COMANDO DO COMANDO MILITAR DA AMAZÔNIA', 'CMA', '4715', '2', '3', '18');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('34', 'COMISSÃO REGIONAL DE OBRAS DA 12ª REGIÃO MILITAR', 'CRO 12', '2061', '2', '3', '18');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('35', 'COMPANHIA DE COMANDO DA 12º REGIÃO MILITAR', 'CIA C 12ª RM', '6155', '2', '3', '18');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('36', 'COMPANHIA DE COMANDO DO 2º GRUPAMENTO DE ENGENHARIA', 'CIA C 2º GPT E', '6800', '2', '3', '18');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('37', 'COMPANHIA DE COMANDO DO COMANDO MILITAR DA AMAZÔNIA', 'CMA', '4715', '2', '3', '18');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('38', 'PARQUE REGIONAL DE MANUTENÇÃO DA 12ª REGIÃO MILITAR', 'PQ R MNT/12', '1985', '2', '3', '18');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('28', '69065060', 'RUA PROFESSOR ERNANI SIMÃO', 'CACHOEIRINHA', '256');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('39', 'HOSPITAL MILITAR DE ÁREA DE MANAUS', 'HMAM', '1421', '2', '3', '28');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('29', '69555180', 'ESTRADA DO AEROPORTO', 'AEROPORTO', '276');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('40', '16ª BASE LOGÍSTICA', '16ª BA LOG', '2801', '2', '3', '29');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('30', '69555300', 'ESTRADA DO AEROPORTO', 'AEROPORTO', '276');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('41', '16º PELOTÃO DE COMUNICAÇÕES DE SELVA', '16º PEL COM SL', 'S/N', '2', '3', '30');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('42', '34º PELOTÃO DE POLÍCIA DO EXÉRCITO', '34º PEL PE', 'S/N', '2', '3', '29');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('31', '69470000', 'RUA OLAVO BILAC', 'CENTRO', '276');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('43', '4ª DELEGACIA DO SERVIÇO MILITAR DA 29ª CSM', '4ª DSM/29ª CSM', '406', '2', '3', '31');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('44', 'Comando da 16ª Brigada de Infantaria de Selva', '16º BDA INF SL', '4174', '2', '3', '30');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('45', 'Companhia de Comando da 16ª Brigada de Infantaria de Selva', 'CIA C 16º BDA INF SL', '4174', '2', '3', '30');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('32', '69151000', 'AVENIDA AMAZONAS', 'CENTRO', '264');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('46', '1ª Delegacia do Serviço Militar da 29ª CSM', '1ª DSM/29ª CSM', '832', '2', '3', '32');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('33', '69750000', 'Área Militar Capitão Nobuo Oba', 'CACHOEIRINHA', '270');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('47', '21ª Companhia de Engenharia de Construção', '21ª CIA E CNST', 'S/N', '2', '3', '33');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('48', '22º Pelotão de Polícia do Exército', '22º PEL PE', 'S/N', '2', '3', '33');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('49', '2º Pelotão de Comunicações de Selva', '2º PEL COM SL', 'S/N', '2', '3', '33');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('50', 'Comando da 2ª Brigada de Infantaria de Selva', '2º BDA INF SL', 'S/N', '2', '3', '33');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('51', 'Companhia de Comando da 2ª Brigada de Infantaria de Selva', 'CIA C 2º BDA INF SL', 'S/N', '2', '3', '33');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('34', '69750000', 'AVENIDA CAPITÃO JOSÉ SILVA DELGADO', 'CACHOEIRINHA', '270');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('52', 'Comando de Fronteira -Rio Negro e 5º Batalhão de Infantaria de Selva', 'CMDO FRON RN/5º BIS', '1761', '2', '3', '34');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('35', '69750000', 'RUA QUINTINO DE SÁ CAVALCANTI', 'DABARU', '270');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('53', 'Hospital de Guarnição de São Gabriel da Cachoeira', 'H GU SGC', '250', '2', '3', '35');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('36', '69104128', 'RUA EDUARDO RIBEIRO', 'JAUARI I', '247');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('54', '2ª Delegacia do Serviço Militar da 29ª CSM', '2ª DSM /29ª CSM', '2845', '2', '3', '36');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('37', '69800000', 'BR 319 - KM 9 Zona Rural', 'Zona rural', '244');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('55', '54º Batalhão de Infantaria de Selva', '54º BIS', 'S/N', '2', '3', '37');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('38', '69640000', 'Avenida da Amizade', 'Centro', '274');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('56', '5ª Delegacia do Serviço Militar da 29ª CSM', '5ª DSM /29ª CSM', '1770', '2', '3', '38');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('57', 'Hospital de Guarnição de Tabatinga', 'H GU T', 'S/N', '2', '3', '38');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('39', '69800000', 'RUA BENJAMIN CONSTANT', 'Centro', '244');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('58', '6ª Delegacia do Serviço Militar da 29ª CSM', '6ª DSM /29ª CSM', '46', '2', '3', '39');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('40', '69700000', 'Rua Tenreiro Aranha', 'Centro', '226');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('59', '7ª Delegacia do Serviço Militar da 29ª CSM', '7ª DSM /29ª CSM', '280', '2', '3', '40');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('41', '69640000', 'PRACA COLÔMBIA', 'Centro', '274');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('60', 'Comando de Fronteira - Solimões e 8º Batalhão de Infantaria de Selva', 'CMDO FRON SOL/8º BIS', 'S/N', '2', '3', '41');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('42', '69280000', 'ESTRADA DO ARCAL', 'MAZZARELLO', '257');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('61', 'Tiro de Guerra de Manicore', 'TG 12-002', 'S/N', '2', '3', '42');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('43', '69700000', 'Avenida Frei Matias Boa Ventura', 'Mariuá', '226');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('62', '3º Batalhão de Infantaria de Selva', '3º BIS', 'S/N', '2', '3', '43');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('63', '17º BATALHÃO DE INFANTARIA DE SELVA', '17º BIS', 'S/N', '2', '3', '30');

-- EB: AMAPÁ (ID: 4)
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('44', '68901092', 'RUA ACELINO DE LEÃO', 'TREM', '209');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('64', '6ª Delegacia do Serviço Militar da 28ª CSM', '6ª DSM/28ª CSM', '345', '2', '4', '44');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('45', '68906740', 'AVENIDA PADRE JULIO LOMBAERD', 'ALVORADA', '209');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('65', 'Comando de Fronteira - Amapá e 34º Batalhão de Infantaria de Selva', 'CMDO FRON AP/34º BIS', '4301', '2', '4', '45');

-- EB: BAHIA (ID: 5)
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('46', '48970000', 'RUA DOIS DE JULHO', 'CENTRO', '650');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('66', '11ª Delegacia do Serviço Militar da 17ª CSM', '11ª DSM/17ª CSM', '488', '2', '5', '46');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('47', '47800100', 'RUA 15 de novembro', 'CENTRO', '318');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('67', '12ª Delegacia do Serviço Militar da 17ª CSM', '12ª DSM/17ª CSM', '18', '2', '5', '47');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('48', '44900000', 'PRAÇA TEOTONIO M. DOURADO FILHO', 'CENTRO', '454');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('68', '13ª Delegacia do Serviço Militar da 17ª CSM', '13ª DSM/17ª CSM', '3', '2', '5', '48');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('49', '48540000', 'RUA DUQUE DE CAXIAS', 'CENTRO', '494');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('69', '14ª Delegacia do Serviço Militar da 17ª CSM', '14ª DSM/17ª CSM', '467', '2', '5', '49');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('50', '40080060', 'RUA Gamboa de Cima', 'Campo Grande', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('70', '17ª Circunscrição de Serviço Militar', '17ª CSM', 'S/N', '2', '5', '50');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('51', '45652020', 'RUA ROTARY', 'CIDADE NOVA', '444');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('71', '18ª Circunscrição de Serviço Militar', '18ª CSM', '180', '2', '5', '51');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('52', '41150000', 'RUA SILVEIRA MARTINS', 'CABULA', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('72', '19º Batalhão de Caçadores', '19º BC', 'S/N', '2', '5', '52');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('53', '48608490', 'RUA DA HARMONIA', 'Alves de Souza', '574');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('73', '1ª Companhia de Infantaria', '1ª CIA INF', 'S/N', '2', '5', '53');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('54', '41900020', 'Avenida Amaralina', 'Alves de Souza', '5565');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('74', '1ª Delegacia do Serviço Militar da 17ª CSM', '1ª DSM/17ª CSM', 'S/N', '2', '5', '54');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('55', '45005020', 'Rua Marechal Mascarenhas de Morais', 'Alto Maron', '693');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('75', '1ª Delegacia do Serviço Militar da 18ª CSM', '1ª DSM/18ª CSM', 'S/N', '2', '5', '55');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('56', '46900000', 'Praça Benjamin Constant', 'CENTRO', '648');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('76', '2ª Delegacia do Serviço Militar da 17ª CSM', '2ª DSM/17ª CSM', '168', '2', '5', '56');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('57', '45600124', 'PRAÇA LAURA CONCEIÇÃO', 'CENTRO', '457');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('77', '2ª Delegacia do Serviço Militar da 18ª CSM', '2ª DSM/18ª CSM', '319', '2', '5', '57');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('58', '44094000', 'Avenida Eduardo Froes da Mota', 'Subaé', '411');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('78', '35º Batalhão de Infantaria', '35º BI', '7770', '2', '5', '58');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('59', '48005170', 'Praça ALFREDO ARAUJO', 'CENTRO', '287');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('79', '3ª Delegacia do Serviço Militar da 17ª CSM', '3ª DSM/17ª CSM', '11', '2', '5', '59');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('60', '45203010', 'RUA MILTON MUNIZ', 'CENTRO', '493');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('80', '3ª Delegacia do Serviço Militar da 18ª CSM', '3ª DSM/18ª CSM', '17', '2', '5', '60');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('61', '46100000', 'Avenida Ana Lídia Viana Cardoso', 'Parque Alvorada', '336');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('81', '4ª Delegacia do Serviço Militar da 18ª CSM', '3ª DSM/18ª CSM', '586', '2', '5', '61');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('62', '47810902', 'ROV BR 020/242 - KM 03', 'MORADA NOBRE', '318');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('82', '4º Batalhão de Engenharia de Construção', '4º BEC', 'S/N', '2', '5', '62');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('63', '41730101', 'Avenida Luiz Viana Filho', 'Bolandeira', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('83', '51º Centro de Telemática', '51º CT', 'S/N', '2', '5', '63');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('64', '48700000', 'AVENIDA ANTONIO CARLOS MAGALHÃES', 'Centro', '655');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('84', '5ª Delegacia do Serviço Militar da 17ª CSM', '5ª DSM/17ª CSM', '250', '2', '5', '64');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('65', '41180000', 'Avenida Governador Luís Viana Filho', 'Imbuí', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('85', '6º Batalhão de Polícia do Exército', '6º BPE', 'S/N', '2', '5', '65');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('66', '40060008', 'RUA GAMBOA DE CIMA', 'Dois de Julho', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('86', '6º Depósito de Suprimento', '6º D SUP', 'S/N', '2', '5', '65');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('67', '44700000', 'PRAÇA RIO BRANCO', 'Centro', '488');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('87', '7ª Delegacia do Serviço Militar da 17ª CSM', '7ª DSM/17ª CSM', 'S/N', '2', '5', '67');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('68', '44002232', 'AVENIDA GETULIO VARGAS', 'Centro', '411');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('88', '9ª Delegacia do Serviço Militar da 17ª CSM', '9ª DSM/17ª CSM', 'S/N', '2', '5', '68');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('69', '40040110', 'Praça Duque de Caxias', 'Nazaré', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('89', 'Comando da 6ª Região Militar', '6ª RM', 'S/N', '2', '5', '69');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('90', 'Companhia de Comando da 6ª Região Militar', 'CIA C 6ª RM', 'S/N', '2', '5', '69');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('70', '41830540', 'Rua Território do Amapá', 'Pituba', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('91', 'Escola de Formação Complementar do Exército', 'ESFCEX', '455', '2', '5', '70');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('71', '41810010', 'Rua DAS HORTÊNSIAS', 'Pituba', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('92', 'Colégio Militar de Salvador', 'CMS', 'S/N', '2', '5', '71');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('72', '40255020', 'Rua Castro Neves', 'MATATU', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('93', 'Hospital Geral de Salvador', 'H GE S', '72', '2', '5', '72');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('73', '40414610', 'Rua DA BOA VIAGEM', 'BOA VIAGEM', '616');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('94', 'Parque Regional de Manutenção da 6ª Região Militar', 'PQ R MNT/6', 'S/N', '2', '5', '73');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('74', '44300000', 'Avenida Virgílio Reis', 'Centro', '341');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('95', 'Tiro de Guerra de Cachoeira', 'TG 06-002', 'S/N', '2', '5', '74');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('75', '44571003', 'Rua Tenente-Coronel Bandeira de Melo', 'Calabar', '630');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('96', 'Tiro de Guerra de Santo Antônio de Jesus', 'TG 06-003', 'S/N', '2', '5', '75');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('76', '44380000', 'Rua Henrique José de Andrade', 'Ana Lúcia', '396');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('97', 'Tiro de Guerra de Cruz das Almas', 'TG 06-004', '132', '2', '5', '76');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('77', '45400000', 'Avenida Daniel Ribeiro Soares', 'Novo Horizonte', '685');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('98', 'Tiro de Guerra de Valença', 'TG 06-005', 'S/N', '2', '5', '77');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('78', '45000625', 'Praça Sá Barreto', 'Centro', '693');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('98', 'Tiro de Guerra de Vitória da Conquista', 'TG 06-006', '43', '2', '5', '78');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('79', '45608500', 'Rua D', 'Vila Anália', '457');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('99', 'Tiro de Guerra de Itabuna', 'TG 06-007', '506-600', '2', '5', '79');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('80', '44700000', 'Praça Presidente Kennedy', 'Estação', '488');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('99', 'Tiro de Guerra de Jacobina', 'TG 06-008', '96', '2', '5', '80');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('81', '45204020', 'Rua 31 de Março', 'Campo do América', '493');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('100', 'Tiro de Guerra de Jequié', 'TG 06-009', 'S/N', '2', '5', '81');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('82', '45260000', 'Rua Saturnino Macedo', 'Centro', '588');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('101', 'Tiro de Guerra de Poções', 'TG 06-011', '41', '2', '5', '82');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('83', '48700000', 'Rua Campos Filho', 'Centro', '655');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('102', 'Tiro de Guerra de Serrinha', 'TG 06-014', '449', '2', '5', '83');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('84', '44400000', 'Praça Narciso Pitanga', 'Centro', '552');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('103', 'Tiro de Guerra de Nazaré', 'TG 06-020', '07', '2', '5', '84');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('85', '45700000', 'Avenida Cinquentenário', 'PRIMAVERA', '474');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('104', 'Tiro de Guerra de Itapetinga', 'TG 06-023', '999', '2', '5', '85');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('86', '46100000', 'Avenida Ana Lídia Viana Cardoso', 'Novo Brumado', '336');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('105', 'Tiro de Guerra de Brumado', 'TG 06-024', '586', '2', '5', '86');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('87', '45836000', 'Rua São Bento', 'Várzea Alegre', '466');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('106', 'Tiro de Guerra de Itamaraju', 'TG 06-025', '400', '2', '5', '87');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('88', '42808010', 'Avenida Radial C', 'Alto da Cruz', '350');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('107', 'Tiro de Guerra de Camaçari', 'TG 06-026', '396-564', '2', '5', '88');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('89', '44900000', 'Praça Cleriston Andrade', 'Centro', '454');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('108', 'Tiro de Guerra de Irecê', 'TG 06-027', 'S/N', '2', '5', '89');

-- EB: CEARA(ID: 6)
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('90', '62320000', 'Rua Capitão Odilon Aguiar', 'Centro', '871');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('109', '10ª Delegacia do Serviço Militar da 25ª CSM', '10ª DSM/25ª CSM', '431', '2', '6', '90');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('91', '60860540', 'Avenida Marechal Bittencourt', 'Dias Macedo', '756');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('110', '10º Deposito de Suprimento', '10º D SUP', '100', '2', '6', '91');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('92', '62760000', 'Praça da Matriz', 'Centro', '724');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('111', '13ª Delegacia do Serviço Militar da 25ª CSM', '13ª DSM/25ª CSM', 'S/N', '2', '6', '92');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('93', '60410690', 'Avenida Luciano Carneiro', 'Fátima', '756');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('112', '16ª Companhia de Polícia do Exército', '16ª CIA PE', '840', '2', '6', '93');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('94', '61940135', 'Rua Capistrano de Abreu', 'Centro', '802');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('113', '1ª Delegacia do Serviço Militar da 25ª CSM', '1ª DSM/25ª CSM', 'S/N', '2', '6', '94');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('95', '60040531', 'Avenida 13 de Maio', 'Fátima', '756');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('114', '23º Batalhão de Caçadores', '23º BC', '1589', '2', '6', '95');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('115', '25ª Circunscrição de Serviço Militar', '25ª CSM', '840', '2', '6', '93');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('96', '63500119', 'RUA DEOCLECIANO BEZERRA', 'Centro', '774');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('116', '2ª Delegacia do Serviço Militar da 25ª CSM', '2ª DSM/25ª CSM', '778', '2', '6', '96');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('97', '83900000', 'Rua Tabelião Enéias', 'Centro', '846');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('117', '3ª Delegacia do Serviço Militar da 25ª CSM', '3ª DSM/25ª CSM', '95', '2', '6', '97');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('98', '63700000', 'BR 226', 'VENÂNCIOS', '747');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('118', '40º Batalhão de Infantaria', '40º BI', 'KM 3', '2', '6', '97');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('99', '63100380', 'Rua Araripe', 'Centro', '748');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('119', '4ª Delegacia do Serviço Militar da 25ª CSM', '4ª DSM/25ª CSM', '384', '2', '6', '99');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('120', '52º Centro de Telemática', '52º CT', '840', '2', '6', '93');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('100', '63700000', 'Rua Barão do Rio Branco', 'Fátima I', '747');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('121', '5ª Delegacia do Serviço Militar da 25ª CSM', '5ª DSM/25ª CSM', '1679', '2', '6', '100');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('101', '62011000', 'Praça da Sé', 'Centro', '864');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('122', '6ª Delegacia do Serviço Militar da 25ª CSM', '6ª DSM/25ª CSM', '5', '2', '6', '101');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('102', '60115000', 'Rua Idelfonso Albano', 'Ginásio Paulo Sarasate Aldeota', '756');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('123', '7ª Delegacia do Serviço Militar da 25ª CSM', '7ª DSM/25ª CSM', 'S/N', '2', '6', '102');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('103', '62930000', 'Rua Coronel Antonio Joaquim', 'Centro', '799');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('124', '8ª Delegacia do Serviço Militar da 25ª CSM', '8ª DSM/25ª CSM', '1564', '2', '6', '103');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('104', '62500000', 'Rua Elbia Barroso', 'Centro', '799');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('125', '9ª Delegacia do Serviço Militar da 25ª CSM', '8ª DSM/25ª CSM', '2572', '2', '6', '104');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('105', '60150160', 'AVENIDA SANTOS DUMONT', 'ALDEOTA', '756');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('126', 'Colégio Militar de Fortaleza', 'CMF', 'S/N', '2', '6', '105');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('106', '60051970', 'Avenida Alberto Nepomuceno', 'CENTRO', '756');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('127', 'Comando da 10ª Região Militar', '10ª RM', 'S/N', '2', '6', '106');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('128', 'Companhia de Comando da 10ª Região Militar', 'CIA C 10ª RM', 'S/N', '2', '6', '106');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('107', '60170001', 'AVENIDA DESEMBARGADOR MOREIRA', 'ALDEOTA', '756');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('129', 'Hospital Geral de Fortaleza', 'H GE F', '1500', '2', '6', '107');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('108', '60415540', 'AVENIDA EDUARDO GIRAO', 'Fátima', '756');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('130', 'Parque Regional de Manutenção da 10ª Região Militar', 'PQ R MNT/10', '1533', '2', '6', '108');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('131', 'Seção de Fiscalização de Produtos Controlados da 10ª Região Militar', 'SFPC/10', 'S/N', '2', '6', '106');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('109', '63024530', 'Av 31 de Março', 'TRIÂNGULO', '796');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('132', 'Tiro de Guerra de Juazeiro do Norte', 'TG 10-005', 'S/N', '2', '6', '109');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('110', '62580000', 'Rua Duque de Caxias', 'Outra Banda', '700');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('133', 'Tiro de Guerra de Acaraú', 'TG 10-018', '56', '2', '6', '110');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('111', '62800000', 'RUA Beni CARVALHO', 'NOSSA SENHORA DE LOURDES', '710');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('134', 'Tiro de Guerra de Aracati', 'TG 10-014', 'S/N', '2', '6', '111');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('112', '62400000', 'RUA HUMAITÁ', 'SÃO PEDRO', '729');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('135', 'Tiro de Guerra de Camocim', 'TG 10-001', '2735', '2', '6', '112');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('113', '63100482', 'RUA RUI BARBOSA', 'CENTRO', '748');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('136', 'Tiro de Guerra de Crato', 'TG 10-004', 'S/N', '2', '6', '113');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('114', '63500000', 'RUA 25 DE MARÇO', 'AEROPORTO', '774');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('137', 'Tiro de Guerra de IGUATU', 'TG 10-013', 'S/N', '2', '6', '114');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('115', '62500000', 'Avenida Anastácio Braga', 'FAZENDINHA', '785');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('138', 'Tiro de Guerra de ITAPIPOCA', 'TG 10-015', 'S/N', '2', '6', '115');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('116', '62930000', 'RUA CORONEL JOSE NUNES', 'C POPULARES', '799');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('139', 'Tiro de Guerra de LIMOEIRO DO NORTE', 'TG 10-006', 'S/N', '2', '6', '116');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('117', '63900000', 'PRAÇA DO ATIRADOR', 'CAMPO NOVO', '846');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('140', 'Tiro de Guerra de QUIXADÁ', 'TG 10-016', 'S/N', '2', '6', '117');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('118', '62900000', 'AVENIDA GOVERNADOR RAUL BARBOSA', 'ALTO DA BOA VISTA', '852');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('141', 'Tiro de Guerra de RUSSAS', 'TG 10-010', 'S/N', '2', '6', '118');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('119', '62050470', 'Rua Engenheiro Jose Figueiredo', 'SINHÁ SABÓIA', '864');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('142', 'Tiro de Guerra de SOBRAL', 'TG 10-011', '1035', '2', '6', '119');
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('120', '63750000', 'RUA FRANKLIN CAVALCANTE', 'MONTE CASTELO', '867');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('143', 'Tiro de Guerra de TAMBORIL', 'TG 10-022', 'S/N', '2', '6', '120');

-- EB: DISTRITO FEDERAL(ID: 7)
INSERT INTO `Endereco` (`id`, `cep`, `descricao`, `bairro`, `idCidade`) VALUES ('121', '70050906', 'ANEXO AO EDIFÍCIO DO COMANDO DO EXÉRCITO BRASILEIRO', 'MONTE CASTELO', '867');
INSERT INTO `OM` (`id`, `nome`, `abreviatura`, `numendereco`, `idForca`, `idEstado`, `idEndereco`) VALUES ('144', '11ª Inspetoria de Contabilidade e Finanças do Exército', '11ª ICFEX', 'S/N', '2', '6', '121');




